/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.g5.form;

import com.g5.entity.SanPhamKM;
import com.g5.entityDAO.KhuyenMaiDAO;
import com.g5.entityDAO.KhuyenMaiSPDAO;
import com.g5.util.Auth;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import com.g5.entity.*;
import com.g5.util.JDBCHelper;
import static com.g5.util.JDBCHelper.props;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.sql.*;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.lang.Math.round;
import java.util.ArrayList;
import java.util.Properties;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ButtonGroup;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author sora6
 */
public class KhuyenMaiJpanel extends javax.swing.JPanel {

    public static final Properties props = JDBCHelper.loadDbProperties();
    int currentFilterColumn = 1;
    String MaKM = "0";
    KhuyenMaiDAO kmDAO = new KhuyenMaiDAO();
    KhuyenMaiSPDAO kmspDAO = new KhuyenMaiSPDAO();
    int choose;

    /**
     * Creates new form KhuyenMai
     */
    public KhuyenMaiJpanel() {
        initComponents();
        txtManv.setText(Auth.user.getMaNV() + "");
        fillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtKM = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtManv = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtBatdau = new com.toedter.calendar.JDateChooser();
        txtKetthuc = new com.toedter.calendar.JDateChooser();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSP = new javax.swing.JTable();
        txtChietkhau = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblKM = new javax.swing.JTable();
        btnAddSp = new javax.swing.JButton();
        lbChoosen = new javax.swing.JLabel();

        setName("Test"); // NOI18N

        jLabel1.setText("Thông tin chương trình");

        jLabel2.setText("Tên chương trình (có thể ghi dấu):");

        jLabel3.setText("Mã NV:");

        jLabel4.setText("Chiết khấu (%): ");

        txtManv.setEditable(false);
        txtManv.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel5.setText("Ngày bắt đầu");

        jLabel6.setText("Ngày kết thúc");

        txtBatdau.setDateFormatString("yyyy-MM-dd");
        //txtBatdau.setLocale(new Locale("vi", "VN"));

        txtKetthuc.setDateFormatString("yyyy-MM-dd");
        //txtKetthuc.setLocale(new Locale("vi", "VN"));

        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("Cập nhật");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnNew.setText("Làm mới");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnDel.setText("Xóa");
        btnDel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDelMouseClicked(evt);
            }
        });
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        tblSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã Sp", "Tên Sp", "Giá gốc", "Giá KM"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblSP);
        if (tblSP.getColumnModel().getColumnCount() > 0) {
            tblSP.getColumnModel().getColumn(0).setResizable(false);
            tblSP.getColumnModel().getColumn(1).setResizable(false);
            tblSP.getColumnModel().getColumn(2).setResizable(false);
            tblSP.getColumnModel().getColumn(3).setResizable(false);
            tblSP.getColumnModel().getColumn(4).setResizable(false);
        }

        tblKM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã KM", "Tên khuyến mãi", "Ngày bắt đầu", "Ngày kết thúc", "Mã NV", "Chiết khấu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKM.setRowHeight(50);
        tblKM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKMMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblKM);
        if (tblKM.getColumnModel().getColumnCount() > 0) {
            tblKM.getColumnModel().getColumn(0).setMaxWidth(50);
            tblKM.getColumnModel().getColumn(1).setMaxWidth(50);
            tblKM.getColumnModel().getColumn(2).setResizable(false);
            tblKM.getColumnModel().getColumn(3).setResizable(false);
            tblKM.getColumnModel().getColumn(4).setResizable(false);
            tblKM.getColumnModel().getColumn(5).setMaxWidth(50);
            tblKM.getColumnModel().getColumn(6).setResizable(false);
        }

        btnAddSp.setText("Thêm sản phẩm");
        btnAddSp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSpActionPerformed(evt);
            }
        });

        lbChoosen.setText("Mã KM : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtManv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 911, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(8, 8, 8)
                                        .addComponent(txtChietkhau))
                                    .addComponent(txtKM, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtBatdau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtKetthuc, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lbChoosen)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAddSp))
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(txtBatdau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(txtKetthuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtChietkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtManv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbChoosen)
                            .addComponent(btnAddSp))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        try {
            insertKM(getForm());
            JOptionPane.showMessageDialog(this, "Them thanh cong!!!");
            fillTable();
            clearForm();
            btnDel.setEnabled(false);
            btnUpdate.setEnabled(false);
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_btnAddActionPerformed

    private void tblKMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKMMouseClicked
        // TODO add your handling code here:
        choose = tblKM.getSelectedRow();
        lbChoosen.setText("Mã KM : " + tblKM.getValueAt(choose, 1));
        fillform();
        fillTableSp((int) tblKM.getValueAt(choose, 1));
        MaKM = tblKM.getValueAt(choose, 1) + "";
        btnDel.setEnabled(true);
        btnUpdate.setEnabled(true);
        btnAddSp.setEnabled(true);
    }//GEN-LAST:event_tblKMMouseClicked

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try {
            updateKM(getForm());
            JOptionPane.showMessageDialog(this, "Sua thanh cong!!!");
            fillTable();
            clearForm();
            btnDel.setEnabled(false);
            btnUpdate.setEnabled(false);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
        try {
            deleteKM((Integer) tblKM.getValueAt(choose, 1));
            JOptionPane.showMessageDialog(this, "Xoa thanh cong khuyen mai so " + tblKM.getValueAt(choose, 0));
            fillTable();
            clearForm();
            btnDel.setEnabled(false);
            btnUpdate.setEnabled(false);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnDelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDelMouseClicked

    private void btnAddSpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSpActionPerformed
        currentFilterColumn = 1;
        Frame frame = null;
        JDialog dialog = new JDialog(frame, "Thêm sản phẩm", true);
        dialog.setSize(800, 500);
        dialog.setLocationRelativeTo(frame);

        String[] columnNames = {"    ", "Mã SP", "Tên SP", "Giá"};
        Object[][] data = getSanPhamData(tblKM.getValueAt(choose, 1) + "");

        DefaultTableModel model = new DefaultTableModel(data, columnNames) {
            @Override
            public Class<?> getColumnClass(int column) {
                switch (column) {
                    case 0:
                        return Boolean.class;
                    default:
                        return String.class;
                }
            }
        };
        JTable table = new JTable(model);
        table.setPreferredScrollableViewportSize(new Dimension(600, 100));
        table.getColumnModel().getColumn(0).setPreferredWidth(50);
        table.getColumnModel().getColumn(1).setPreferredWidth(100);
        table.getColumnModel().getColumn(2).setPreferredWidth(350);

        table.getColumnModel().getColumn(0).setCellEditor(new DefaultCellEditor(new JCheckBox()));
        JScrollPane scrollPane = new JScrollPane(table);

        JButton updateButton = new JButton("Cập nhật");

        boolean[] initialState = new boolean[table.getRowCount()];
        for (int i = 0; i < table.getRowCount(); i++) {
            initialState[i] = (Boolean) table.getValueAt(i, 0);
        }

        JTextField searchField = new JTextField();
        updateButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                searchField.setText("");
                // Duyệt qua tất cả các hàng trong bảng
                for (int i = 0; i < table.getRowCount(); i++) {
                    int modelIndex = table.convertRowIndexToModel(i); // Chuyển đổi chỉ số hàng
                    Boolean isChecked = (Boolean) table.getModel().getValueAt(modelIndex, 0);
                    String maSP = (String) table.getModel().getValueAt(modelIndex, 1);

                    if (isChecked != initialState[modelIndex]) {
                        updateSanPham(maSP, isChecked);
                    }
                }
                fillTableSp((int) tblKM.getValueAt(choose, 1));
                JOptionPane.showMessageDialog(null, "Cập nhật thành công!!");
                dialog.dispose();
            }
        });
        searchField.setPreferredSize(new Dimension(400, 35));
        searchField.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        JPanel searchPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        searchPanel.add(searchField);

        ButtonGroup buttonGroup = new ButtonGroup();

        JRadioButton maSPButton = new JRadioButton("Theo mã SP");
        maSPButton.setSelected(true);
        buttonGroup.add(maSPButton);

        JRadioButton tenSPButton = new JRadioButton("Theo tên SP");
        buttonGroup.add(tenSPButton);
        maSPButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                currentFilterColumn = 1;
                searchField.setText("");
            }
        });

        tenSPButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                currentFilterColumn = 2;
                searchField.setText("");
            }
        });

        searchField.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                filter();
            }

            public void removeUpdate(DocumentEvent e) {
                filter();
            }

            public void insertUpdate(DocumentEvent e) {
                filter();
            }

            public void filter() {
                String filterText = searchField.getText().toLowerCase();
                TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>((DefaultTableModel) table.getModel());
                table.setRowSorter(sorter);
                sorter.setRowFilter(new RowFilter<DefaultTableModel, Integer>() {
                    @Override
                    public boolean include(RowFilter.Entry<? extends DefaultTableModel, ? extends Integer> entry) {

                        String cellValue = entry.getStringValue(currentFilterColumn).toLowerCase();
                        return cellValue.contains(filterText);
                    }
                });
            }
        });

        JPanel radioPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        radioPanel.add(maSPButton);
        radioPanel.add(tenSPButton);

        JLabel searchLabel = new JLabel("Tìm kiếm");

        JPanel searchFieldPanel = new JPanel();
        searchFieldPanel.setLayout(new BoxLayout(searchFieldPanel, BoxLayout.X_AXIS));
        searchFieldPanel.add(searchField);

        JPanel searchAndRadioPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        searchAndRadioPanel.add(searchLabel);
        searchAndRadioPanel.add(searchFieldPanel);
        searchAndRadioPanel.add(radioPanel);

        JPanel northPanel = new JPanel(new BorderLayout());
        northPanel.add(searchAndRadioPanel, BorderLayout.NORTH);

        dialog.add(northPanel, BorderLayout.NORTH);
        dialog.add(updateButton, BorderLayout.SOUTH);
        dialog.add(scrollPane);

        dialog.setVisible(true);
    }//GEN-LAST:event_btnAddSpActionPerformed
        String url = props.getProperty("url")+props.getProperty("dtbname");
        String user = props.getProperty("user");
        String pass = props.getProperty("pass");
    
    public Object[][] getSanPhamData(String maKM) {
        ArrayList<Object[]> data = new ArrayList<Object[]>();
        try {
//            Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=THECOFFEE_DUAN1;user=sa;password=123");
            Connection conn = DriverManager.getConnection(url, user, pass);
            String sql = "SELECT  SanPham.MaSP, SanPham.TenSP, MAX(CASE WHEN MaKM = ? THEN 1 ELSE 0 END) AS IsInKM , GSP.Gia FROM SanPham LEFT JOIN KhuyenMaiChiTiet ON SanPham.MaSP = KhuyenMaiChiTiet.MaSP \n"
                    + "JOIN GiaSanPham GSP on GSP.MaSP = SanPham.MaSP where GSP.Size like '%M%' \n" + "GROUP BY SanPham.MaSP, SanPham.TenSP,GSP.Gia ORDER BY sanpham.masp ;";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, maKM);
            ResultSet rs = stmt.executeQuery();

            while (rs.next()) {
                Object[] row = new Object[4];
                JCheckBox cbbox = new JCheckBox();
                row[0] = rs.getBoolean("IsInKM");
                row[1] = rs.getString("MaSP");
                row[2] = rs.getString("TenSP");
                row[3] = rs.getFloat("Gia");
                data.add(row);
            }

            conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }

        Object[][] array = new Object[data.size()][];
        for (int i = 0; i < data.size(); i++) {
            array[i] = data.get(i);
        }

        return array;
    }

    public void updateSanPham(String maSP, boolean isInKM) {
        try {
            Connection conn = DriverManager.getConnection(url, user, pass);
          //  Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=abc;user=sa;password=123");

            if (isInKM) {

                String sql = "IF EXISTS (SELECT * FROM KhuyenMaiChiTiet WHERE MaSP = ? AND MaKM = ?) UPDATE KhuyenMaiChiTiet SET MaSP = ? WHERE MaKM = ? ELSE INSERT INTO KhuyenMaiChiTiet (MaSP, MaKM) VALUES (?, ?)";
                PreparedStatement stmt = conn.prepareStatement(sql);
                stmt.setString(1, maSP);
                stmt.setString(2, MaKM);
                stmt.setString(3, maSP);
                stmt.setString(4, MaKM);
                stmt.setString(5, maSP);
                stmt.setString(6, MaKM);
                stmt.executeUpdate();
            } else {

                String sql = "DELETE FROM KhuyenMaiChiTiet WHERE MaSP = ? AND MaKM = ?";
                PreparedStatement stmt = conn.prepareStatement(sql);
                stmt.setString(1, maSP);
                stmt.setString(2, MaKM);
                stmt.executeUpdate();
            }

            conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    void clearForm() {
        txtKM.setText("");
        txtChietkhau.setText("");
        txtBatdau.setDate(new Date());
        txtKetthuc.setDate(new Date());
        fillTableSp(0);
        lbChoosen.setText("Mã KM : ");
        txtManv.setText(Auth.user.getMaNV() + "");
        btnDel.setEnabled(false);
        btnUpdate.setEnabled(false);
        btnAddSp.setEnabled(false);
    }

    void deleteKM(int id) {
        kmDAO.deteleByID(id);
    }

    KhuyenMai getForm() {
        KhuyenMai km = new KhuyenMai();
        km.setTenKM(txtKM.getText());
        km.setTGBatDau(txtBatdau.getDate());
        km.setTGKetThuc(txtKetthuc.getDate());
        km.setMaNV(Auth.user.getMaNV());
        float PTkm = Math.round(Float.parseFloat(txtChietkhau.getText()) * 100) / 100.0f;
        km.setPhanTramKM(PTkm);
        km.setMaKM((int) tblKM.getValueAt(choose, 1));
        return km;
    }

    void insertKM(KhuyenMai km) {
        kmDAO.create(km);
    }

    void updateKM(KhuyenMai km) {
        kmDAO.update(km);
    }

    void fillTable() {
        btnDel.setEnabled(false);
        btnUpdate.setEnabled(false);
        btnAddSp.setEnabled(false);
        DefaultTableModel model = (DefaultTableModel) tblKM.getModel();
        model.setRowCount(0);
        List<KhuyenMai> list = kmDAO.getAll();
        int i = 0;
        for (KhuyenMai km : list) {
            i += 1;
            model.addRow(new Object[]{i, km.getMaKM(), km.getTenKM(), km.getTGBatDau(), km.getTGKetThuc(), km.getMaNV(), km.getPhanTramKM()});
        }
    }

    void fillTableSp(int id) {
        DefaultTableModel modelSp = (DefaultTableModel) tblSP.getModel();
        modelSp.setRowCount(0);
        List<SanPhamKM> list = (List<SanPhamKM>) kmspDAO.getByCondition("SELECT * FROM KhuyenMaiChiTiet KMCT JOIN SanPham SP ON KMCT.MaSP = SP.MaSP JOIN GiaSanPham GSP ON SP.MaSP = GSP.MaSP JOIN KhuyenMai KM ON KM.MaKM = KMCT.MaKM WHERE KMCT.MaKM = ? AND GSP.Size like '%M%' ;", id);
        int i = 0;
        for (SanPhamKM sp : list) {
            i += 1;
            modelSp.addRow(new Object[]{i, sp.getMaSP(), sp.getTenSP(), sp.getGia(), sp.getGia() * (1 - sp.getChietkhau())});
        }

    }

    void fillform() {
        txtKM.setText((String) tblKM.getValueAt(choose, 2));
        txtBatdau.setDate((Date) tblKM.getValueAt(choose, 3));
        txtKetthuc.setDate((Date) tblKM.getValueAt(choose, 4));
        txtManv.setText(tblKM.getValueAt(choose, 5) + "");
        txtChietkhau.setText(tblKM.getValueAt(choose, 6) + "");

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddSp;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lbChoosen;
    private javax.swing.JTable tblKM;
    private javax.swing.JTable tblSP;
    private com.toedter.calendar.JDateChooser txtBatdau;
    private javax.swing.JTextField txtChietkhau;
    private javax.swing.JTextField txtKM;
    private com.toedter.calendar.JDateChooser txtKetthuc;
    private javax.swing.JTextField txtManv;
    // End of variables declaration//GEN-END:variables

}
